name: 彭成章 
markdown: kramdown
baseurl: 
permalink: /:title/
paginate: 10
future: true
paginate_path: /blog/page/:num
description: 彭成章个人博客 
url: http://abelard2008.github.io
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from


