markdown: rdiscount
highlighter: true
rdiscount:
  extensions: [smart, autolink]

comments :
   provider: disqus
   disqus:
     short_name:   dillonpengblog

name: Dillon Peng's blog
description: Dillon Peng's computer technology and other stuff blog
url: http://abelard2008.github.com
