name: 彭成章 
# markdown: redcarpet
highligher: pygments
baseurl: 
permalink: /:title/
paginate: 10
future: true
paginate_path: /blog/page/:num
description: 彭成章个人博客 
url: http://abelard2008.github.io
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed
